modLoader = "javafml"
loaderVersion = "[40,)"
license = "gplv3"
issueTrackerURL = "https://github.com/MehVahdJukaar/Moonlight/issues" #optional

[[mods]]
    modId = "moonlight"
    version = "${version}"
    displayName = "Moonlight Library"
    authors = "MehVahdJukaar"
    modUrl = "https://www.curseforge.com/minecraft/mc-mods/selene" #optional
    updateJSONURL = "https://raw.githubusercontent.com/MehVahdJukaar/Moonlight/multi-loader/forge/update.json"

    logoFile="icon.png" #optional
    description = '''
    A small library with many cool unique features, from dynamic asset generation to dynamic villager schedules and simple multi loader utilities
    '''

[[dependencies.moonlight]]
    modId = "forge"
    mandatory = true
    versionRange = "[43.0.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.moonlight]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.4,)"
    ordering = "NONE"
    side = "BOTH"

